client:
  foo:
  bar:
    - arg1
    - arg2
  self:
    foo:
    bar:
      - arg1
      - arg2
    buzz:
      - arg1
      - arg2
      - hash_params:
        - hash_arg1
        - hash_arg2
        - hash_arg3

api_client:
  foo:
  bar:
    - arg1
    - arg2
  self:
    foo:
    bar:
      - arg1
      - arg2

api_client-layer1:
  self:
    foo:
    bar:
      - arg1
      - arg2

api_client-layer1-layer2:
  self:
    foo:
    bar:
      - arg1
      - arg2
